# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secretctl < Formula
  desc "The simplest AI-ready secrets manager"
  homepage "https://github.com/forest6511/secretctl"
  version "0.8.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/forest6511/secretctl/releases/download/v0.8.2/secretctl_0.8.2_darwin_amd64.tar.gz"
      sha256 "fc4cfa46ee06ec987516a8db351ba88a3491658a9258c4201bebca46141ff349"

      def install
        bin.install "secretctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/forest6511/secretctl/releases/download/v0.8.2/secretctl_0.8.2_darwin_arm64.tar.gz"
      sha256 "7fdb6592467db0331c49c60b9907448725e7fc48eaf163241ad2b3df7eb7afbb"

      def install
        bin.install "secretctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/forest6511/secretctl/releases/download/v0.8.2/secretctl_0.8.2_linux_amd64.tar.gz"
      sha256 "62d2c2e48543bbddd243179080afa5c4acc06b790a895cbebf2cc3c8248484bb"
      def install
        bin.install "secretctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/forest6511/secretctl/releases/download/v0.8.2/secretctl_0.8.2_linux_arm64.tar.gz"
      sha256 "885e219bd05c8a4257f7540d3067fe80f6f111d629322239d3a937ed3c062683"
      def install
        bin.install "secretctl"
      end
    end
  end

  test do
    system "#{bin}/secretctl", "version"
  end
end
