# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secretctl < Formula
  desc "The simplest AI-ready secrets manager"
  homepage "https://github.com/forest6511/secretctl"
  version "0.8.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/forest6511/secretctl/releases/download/v0.8.8/secretctl_0.8.8_darwin_amd64.tar.gz"
      sha256 "0c4543e5043abbb3c959fb24f1cb28b03bc0be2e647382220545752a52f3cbb9"

      def install
        bin.install "secretctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/forest6511/secretctl/releases/download/v0.8.8/secretctl_0.8.8_darwin_arm64.tar.gz"
      sha256 "3cfae9bdf5d87e0967d50b30ba2b624d42d341c2c7231117538b424c333c6a21"

      def install
        bin.install "secretctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/forest6511/secretctl/releases/download/v0.8.8/secretctl_0.8.8_linux_amd64.tar.gz"
      sha256 "c50d69c67f975246e2b7fb23e9d1d64eb634593b48e2d788f7eb0aa60235cb55"
      def install
        bin.install "secretctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/forest6511/secretctl/releases/download/v0.8.8/secretctl_0.8.8_linux_arm64.tar.gz"
      sha256 "db72f47eabebf1aa2e0be6c23ce374a24413abb1332822cdf10260341155b9cc"
      def install
        bin.install "secretctl"
      end
    end
  end

  test do
    system "#{bin}/secretctl", "version"
  end
end
